set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR i686)
set(CMAKE_C_COMPILER /opt/mxe/usr/bin/i686-w64-mingw32.static-gcc)
set(CMAKE_CXX_COMPILER /opt/mxe/usr/bin/i686-w64-mingw32.static-g++)
set(CMAKE_RC_COMPILER /opt/mxe/usr/bin/i686-w64-mingw32.static-windres)
set(CMAKE_SYSROOT /opt/mxe/usr/i686-w64-mingw32.static)
set(CMAKE_FIND_ROOT_PATH /opt/mxe/usr/i686-w64-mingw32.static)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_C_FLAGS_INIT "-nostdinc -I${CMAKE_SYSROOT}/include -I/opt/mxe/usr/lib/gcc/i686-w64-mingw32.static/11.5.0/include")
set(CMAKE_CXX_FLAGS_INIT "-nostdinc -I${CMAKE_SYSROOT}/include -I/opt/mxe/usr/lib/gcc/i686-w64-mingw32.static/11.5.0/include/c++ -I/opt/mxe/usr/lib/gcc/i686-w64-mingw32.static/11.5.0/include/c++/i686-w64-mingw32.static")
set(CMAKE_EXE_LINKER_FLAGS "-static-libgcc -static-libstdc++")
set(CMAKE_SHARED_LINKER_FLAGS "-static-libgcc -static-libstdc++")
set(CMAKE_MODULE_LINKER_FLAGS "-static-libgcc -static-libstdc++")
set(CMAKE_AUTOMOC_MOC_OPTIONS "--include=${CMAKE_BINARY_DIR}/moc_predefs.h" "-I${CMAKE_SYSROOT}/include" "-I/opt/mxe/usr/lib/gcc/i686-w64-mingw32.static/11.5.0/include/c++" "-I/opt/mxe/usr/lib/gcc/i686-w64-mingw32.static/11.5.0/include/c++/i686-w64-mingw32.static")
