#include "vah_sensor_batch_materialize.h"
#include "leveldb_storage.h"
#include <algorithm>
#include <iomanip>
#include <sstream>
#include <stdexcept>
namespace {
using namespace VAHSensorBatchMaterialize;
void setR(std::string*r,const std::string&s){if(r)*r=s;}
bool hx(const std::string&s,size_t n){return s.size()==n&&std::all_of(s.begin(),s.end(),[](unsigned char c){return (c>='0'&&c<='9')||(c>='a'&&c<='f');});}
bool dec(const std::string&s,uint64_t&v){if(s.empty()||(s.size()>1&&s[0]=='0'))return false;v=0;for(char c:s){if(c<'0'||c>'9')return false;uint64_t d=c-'0';if(v>(UINT64_MAX-d)/10)return false;v=v*10+d;}return true;}
std::string d20(uint64_t v){std::ostringstream o;o<<std::setw(20)<<std::setfill('0')<<v;return o.str();}
bool validId(const Identity&i){return hx(i.token_id,16)&&hx(i.writer_id,64)&&hx(i.batch_hash,64)&&i.first_sequence>0;}
std::string wrap(LevelDBStorage&db,const std::string&v){return db.computeDataChecksum(v)+"|"+v;}
std::string proofText(const ChainProof&p,const char*magic){const auto&a=p.anchor;std::ostringstream o;o<<magic<<"\n"<<"token_id="<<a.token_id<<"\n"<<"token_type="<<a.token_type<<"\n"<<"epoch="<<a.epoch<<"\n"<<"writer_id="<<a.writer_id<<"\n"<<"first_sequence="<<a.first_sequence<<"\n"<<"last_sequence="<<a.last_sequence<<"\n"<<"event_count="<<a.event_count<<"\n"<<"previous_batch_hash="<<a.previous_batch_hash<<"\n"<<"merkle_root="<<a.merkle_root<<"\n"<<"batch_hash="<<a.batch_hash<<"\n"<<"txid="<<p.txid<<"\n"<<"block_height="<<p.block_height<<"\n"<<"block_hash="<<p.block_hash<<"\n"<<"tx_index="<<p.tx_index<<"\n"<<"finalized_height="<<p.finalized_height<<"\n"<<"finalized_block_hash="<<p.finalized_block_hash<<"\n";return o.str();}
bool sameProof(const ChainProof&a,const ChainProof&b){return serializeProof(a)==serializeProof(b);}
bool proofMatches(const Identity&i,const ChainProof&p){const auto&a=p.anchor;if(!(validId(i)&&a.token_id==i.token_id&&a.writer_id==i.writer_id&&a.batch_hash==i.batch_hash&&a.first_sequence==i.first_sequence&&hx(p.txid,64)&&hx(p.block_hash,64)&&hx(p.finalized_block_hash,64)&&p.block_height<=p.finalized_height))return false;try{(void)VAHSensorBatchAnchor::encodeAnchor(a);}catch(...){return false;}return true;}
std::string checkpointText(const ChainProof&p){std::ostringstream o;o<<CHECKPOINT_MAGIC<<"\n"<<"token_id="<<p.anchor.token_id<<"\nwriter_id="<<p.anchor.writer_id<<"\nlast_sequence="<<p.anchor.last_sequence<<"\nbatch_hash="<<p.anchor.batch_hash<<"\nanchor_txid="<<p.txid<<"\nanchor_block_height="<<p.block_height<<"\nfinalized_height="<<p.finalized_height<<"\n";return o.str();}
std::string eventText(const VAHSensorBatch::Event&e,const ChainProof&p){std::ostringstream o;o<<EVENT_MAGIC<<"\n"<<"token_id="<<p.anchor.token_id<<"\nwriter_id="<<p.anchor.writer_id<<"\nsequence="<<e.sequence<<"\nobserved_at_ms="<<e.observed_at_ms<<"\nfield="<<e.field<<"\npayload_hash="<<e.payload_hash<<"\nbatch_hash="<<p.anchor.batch_hash<<"\nmerkle_root="<<p.anchor.merkle_root<<"\nanchor_txid="<<p.txid<<"\nanchor_block_height="<<p.block_height<<"\n";return o.str();}
}
namespace VAHSensorBatchMaterialize {
std::string confirmedKey(const Identity&i){if(!validId(i))throw std::invalid_argument("sensor materialization identity invalid");return "TOKEN:VAH_SENSOR_CONFIRMED:"+i.token_id+":writer:"+i.writer_id+":batch:"+i.batch_hash;}
std::string recoveryKey(const Identity&i){if(!validId(i))throw std::invalid_argument("sensor materialization identity invalid");return "TOKEN:VAH_SENSOR_RECOVERY:"+i.token_id+":writer:"+i.writer_id+":batch:"+i.batch_hash;}
std::string checkpointKey(const Identity&i){if(!validId(i))throw std::invalid_argument("sensor materialization identity invalid");return "TOKEN:VAH_SENSOR_CHECKPOINT:"+i.token_id+":writer:"+i.writer_id;}
std::string eventKey(const Identity&i,uint64_t seq){if(!validId(i)||!seq)throw std::invalid_argument("sensor event identity invalid");return "TOKEN:VAH_SENSOR_EVENT:"+i.token_id+":writer:"+i.writer_id+":sequence:"+d20(seq);}
std::string serializeProof(const ChainProof&p){return proofText(p,CONFIRMED_MAGIC);}
bool parseProof(const std::string&t,ChainProof&o,std::string*r){if(t.empty()||t.back()!='\n'||t.find('\r')!=std::string::npos){setR(r,"sensor confirmation proof framing invalid");return false;}std::istringstream in(t);std::string line;if(!std::getline(in,line)||line!=CONFIRMED_MAGIC){setR(r,"sensor confirmation proof magic invalid");return false;}const char*ks[]={"token_id","token_type","epoch","writer_id","first_sequence","last_sequence","event_count","previous_batch_hash","merkle_root","batch_hash","txid","block_height","block_hash","tx_index","finalized_height","finalized_block_hash"};std::vector<std::string>v;for(auto*k:ks){if(!std::getline(in,line)){setR(r,"sensor confirmation proof truncated");return false;}std::string p=std::string(k)+"=";if(line.rfind(p,0)!=0){setR(r,"sensor confirmation proof key order invalid");return false;}v.push_back(line.substr(p.size()));}if(std::getline(in,line)){setR(r,"sensor confirmation proof trailing data");return false;}uint64_t ep,fs,ls,ec,bh,ti,fh;if(!dec(v[2],ep)||!dec(v[4],fs)||!dec(v[5],ls)||!dec(v[6],ec)||!dec(v[11],bh)||!dec(v[13],ti)||!dec(v[14],fh)){setR(r,"sensor confirmation proof decimal invalid");return false;}o.anchor={v[0],v[1],ep,fs,ls,ec,v[3],v[7],v[8],v[9]};o.txid=v[10];o.block_height=bh;o.block_hash=v[12];o.tx_index=ti;o.finalized_height=fh;o.finalized_block_hash=v[15];Identity id{o.anchor.token_id,o.anchor.writer_id,o.anchor.batch_hash,o.anchor.first_sequence};if(!proofMatches(id,o)){setR(r,"sensor confirmation proof identity invalid");return false;}return true;}

bool persistRecoveryRequired(LevelDBStorage&db,const Identity&i,const std::string&code,const std::string&txid,const VAHReconciliation::CanonicalView&v,std::string*r){try{if(!validId(i)||code.empty()||code.find('\n')!=std::string::npos||(!txid.empty()&&!hx(txid,64))||!hx(v.finalizedBlockHash,64)){setR(r,"sensor recovery identity invalid");return false;}std::ostringstream o;o<<RECOVERY_MAGIC<<"\n"<<"token_id="<<i.token_id<<"\nwriter_id="<<i.writer_id<<"\nfirst_sequence="<<i.first_sequence<<"\nbatch_hash="<<i.batch_hash<<"\nexpected_txid="<<txid<<"\nfinalized_height="<<v.finalizedHeight<<"\nfinalized_block_hash="<<v.finalizedBlockHash<<"\nrecovery_reason="<<code<<"\n";const std::string val=o.str(),k=recoveryKey(i);std::string raw,old;bool f=false;if(!db.getRaw("contract:"+k,raw,f)){setR(r,"sensor recovery raw read failed");return false;}if(f){if(!db.getContract(k,old)){setR(r,"existing recovery state checksum invalid");return false;}if(old!=val){setR(r,"conflicting recovery-required state");return false;}return true;}leveldb::WriteBatch wb;wb.Put("contract:"+k,wrap(db,val));if(!db.putBatch(wb,true)){setR(r,"sensor recovery-required persistence failed");return false;}std::string rb;if(!db.getContract(k,rb)||rb!=val){setR(r,"sensor recovery-required readback failed");return false;}return true;}catch(const std::exception&e){setR(r,std::string("sensor recovery persistence exception contained: ")+e.what());return false;}}
Outcome materializeConfirmed(LevelDBStorage&db,const Identity&i,const ChainProof&p,const std::vector<VAHAuthorization::AuthorizationRecord>&h,const std::string&root,std::string*r){if(r)r->clear();try{if(!proofMatches(i,p)){setR(r,"confirmed sensor proof does not match requested identity");return Outcome::Rejected;}std::string existing;bool rawFound=false;std::string raw;if(!db.getRaw("contract:"+confirmedKey(i),raw,rawFound)){setR(r,"confirmed receipt raw read failed");return Outcome::Rejected;}if(rawFound){if(!db.getContract(confirmedKey(i),existing)){setR(r,"confirmed receipt checksum invalid");return Outcome::Rejected;}ChainProof old;if(!parseProof(existing,old,r)||!sameProof(old,p)){setR(r,"conflicting confirmed sensor proof");return Outcome::Rejected;}}
VAHSensorBatchAccumulator::StoredBatch s;std::string lr;if(!VAHSensorBatchAccumulator::loadStoredBatch(db,i.token_id,i.writer_id,i.first_sequence,i.batch_hash,h,root,s,&lr)){
 VAHReconciliation::CanonicalView cv{p.finalized_height,p.finalized_block_hash};if(!persistRecoveryRequired(db,i,"CHAIN_CONFIRMED_LOCAL_BATCH_UNREADABLE",p.txid,cv,r))return Outcome::Rejected;setR(r,"CHAIN_CONFIRMED_LOCAL_BATCH_UNREADABLE: "+lr);return Outcome::RecoveryRequired;}
VAHSensorBatchAnchor::Anchor ca;try{ca=VAHSensorBatchAnchor::canonicalAnchorForStoredBatch(s);}catch(const std::exception&e){setR(r,e.what());return Outcome::Rejected;}if(VAHSensorBatchAnchor::encodeAnchor(ca)!=VAHSensorBatchAnchor::encodeAnchor(p.anchor)){setR(r,"confirmed chain anchor differs from exact durable batch");return Outcome::Rejected;}
 const std::string proof=serializeProof(p),cp=checkpointText(p);leveldb::WriteBatch wb;if(!rawFound)wb.Put("contract:"+confirmedKey(i),wrap(db,proof));for(const auto&e:s.batch.events){bool f=false;if(!db.getRaw("contract:"+eventKey(i,e.sequence),raw,f)){setR(r,"sensor event raw read failed");return Outcome::Rejected;}const std::string ev=eventText(e,p);if(f){std::string old;if(!db.getContract(eventKey(i,e.sequence),old)||old!=ev){setR(r,"existing sensor event checksum-invalid/conflicting");return Outcome::Rejected;}}else wb.Put("contract:"+eventKey(i,e.sequence),wrap(db,ev));}
// Exact historical replay after the feed checkpoint has advanced is idempotent.
 if(rawFound){for(const auto&e:s.batch.events){std::string ev;if(!db.getContract(eventKey(i,e.sequence),ev)||ev!=eventText(e,p)){setR(r,"confirmed historical replay event missing/conflicting");return Outcome::Rejected;}}return Outcome::Idempotent;}
 bool cf=false;if(!db.getRaw("contract:"+checkpointKey(i),raw,cf)){setR(r,"sensor checkpoint raw read failed");return Outcome::Rejected;}if(cf){std::string old;if(!db.getContract(checkpointKey(i),old)){setR(r,"sensor checkpoint checksum invalid");return Outcome::Rejected;}std::istringstream ci(old);std::string l;uint64_t last=0;std::string oldBatch;bool gotLast=false,gotBatch=false;while(std::getline(ci,l)){if(l.rfind("last_sequence=",0)==0)gotLast=dec(l.substr(14),last);else if(l.rfind("batch_hash=",0)==0){oldBatch=l.substr(11);gotBatch=hx(oldBatch,64);}}if(!gotLast||!gotBatch||p.anchor.first_sequence!=last+1||p.anchor.previous_batch_hash!=oldBatch){setR(r,"sensor checkpoint conflict; out-of-order or competing materialization");return Outcome::Rejected;}wb.Put("contract:"+checkpointKey(i),wrap(db,cp));}else{if(p.anchor.first_sequence!=1||p.anchor.previous_batch_hash!=std::string(64,'0')){setR(r,"sensor checkpoint missing for non-genesis materialization");return Outcome::Rejected;}wb.Put("contract:"+checkpointKey(i),wrap(db,cp));}if(!db.putBatch(wb,true)){setR(r,"sensor confirmed/event/checkpoint atomic commit failed");return Outcome::Rejected;}
 std::string rb;if(!db.getContract(confirmedKey(i),rb)||rb!=proof){setR(r,"sensor confirmed receipt readback failed");return Outcome::Rejected;}for(const auto&e:s.batch.events){std::string ev;if(!db.getContract(eventKey(i,e.sequence),ev)||ev!=eventText(e,p)){setR(r,"sensor event readback failed");return Outcome::Rejected;}}std::string rc;if(!db.getContract(checkpointKey(i),rc)||rc!=cp){setR(r,"sensor checkpoint readback failed");return Outcome::Rejected;}return Outcome::Materialized;}catch(const std::exception&e){setR(r,std::string("sensor materialization exception contained: ")+e.what());return Outcome::Rejected;}}
}
