#include "vah_sensor_batch_materialize.h"
#include "blockchain.h"
#include "leveldb_storage.h"
#include "tx.h"
#include <algorithm>
#include <sstream>
namespace {
void setR(std::string*r,const std::string&s){if(r)*r=s;}
std::vector<VAHSensorBatchAnchor::OutputSnapshot> outs(const Transaction&t){std::vector<VAHSensorBatchAnchor::OutputSnapshot>v;for(const auto&o:t.vout)v.push_back({o.amount,o.scriptPubKey});return v;}
bool durableIdentity(const std::string&txt,std::string&tail,std::string&txid){if(txt.empty()||txt.back()!='\n')return false;auto nl=txt.find('\n');if(nl==std::string::npos)return false;tail=txt.substr(nl+1);std::istringstream in(tail);std::string line;txid.clear();while(std::getline(in,line))if(line.rfind("txid=",0)==0)txid=line.substr(5);return txid.size()==64;}
}
namespace VAHSensorBatchMaterialize {
Outcome diagnoseAndMaterialize(const Blockchain&chain,LevelDBStorage&db,const Identity&i,const std::vector<VAHAuthorization::AuthorizationRecord>&h,const std::string&root,const VAHReconciliation::CanonicalView&v,uint64_t first,std::string*r){if(r)r->clear();try{if(first>v.finalizedHeight||v.finalizedHeight-first+1>2048){setR(r,"sensor closeout confirmation range invalid");return Outcome::Rejected;}std::string prepared,watch,pt,wt,expectedTxid;if(!db.getContract("TOKEN:VAH_SENSOR_ANCHOR_PREPARED:"+i.token_id+":writer:"+i.writer_id+":batch:"+i.batch_hash,prepared)||!db.getContract("TOKEN:VAH_SENSOR_ANCHOR_WATCH:"+i.token_id+":writer:"+i.writer_id+":batch:"+i.batch_hash,watch)||!durableIdentity(prepared,pt,expectedTxid)){setR(r,"sensor closeout requires exact strict prepared/watch state");return Outcome::Rejected;}std::string watchTxid;if(!durableIdentity(watch,wt,watchTxid)||pt!=wt||watchTxid!=expectedTxid){setR(r,"sensor closeout prepared/watch identity mismatch");return Outcome::Rejected;}
 std::vector<VAHSensorBatchAnchor::BlockSnapshot> bs;ChainProof proof;bool foundExact=false,foundCompeting=false;for(uint64_t ht=first;ht<=v.finalizedHeight;++ht){auto ob=chain.getBlockByHeight(ht);if(!ob){setR(r,"active-chain block missing during sensor closeout");return Outcome::Rejected;}VAHSensorBatchAnchor::BlockSnapshot b;b.height=ht;b.blockHash=ob->blockHash;b.previousBlockHash=ob->header.prevHash;for(size_t ti=0;ti<ob->transactions.size();++ti){const auto&tx=ob->transactions[ti];Transaction c=tx;c.computeTxId();VAHSensorBatchAnchor::TxSnapshot ts;ts.txid=c.txid;ts.outputs=outs(tx);b.transactions.push_back(ts);for(const auto&o:ts.outputs){VAHSensorBatchAnchor::Anchor a;std::string rr;if(VAHSensorBatchAnchor::parseAnchor(o.scriptPubKey,a,rr)==VAHSensorBatchAnchor::ParseStatus::Valid&&o.amount==0&&a.token_id==i.token_id&&a.writer_id==i.writer_id&&a.batch_hash==i.batch_hash&&a.first_sequence==i.first_sequence){if(ts.txid!=expectedTxid){foundCompeting=true;continue;}if(foundExact){setR(r,"exact prepared sensor anchor txid appears more than once in canonical view");return Outcome::Rejected;}proof.anchor=a;proof.txid=ts.txid;proof.block_height=ht;proof.block_hash=b.blockHash;proof.tx_index=ti;proof.finalized_height=v.finalizedHeight;proof.finalized_block_hash=v.finalizedBlockHash;foundExact=true;}}}bs.push_back(std::move(b));}
 if(chain.getBlockHashByHeight((int)v.finalizedHeight)!=v.finalizedBlockHash){setR(r,"active-chain finalized view changed during sensor closeout");return Outcome::Rejected;}for(size_t x=1;x<bs.size();++x)if(bs[x].height!=bs[x-1].height+1||bs[x].previousBlockHash!=bs[x-1].blockHash){setR(r,"sensor closeout snapshot is not contiguous active-chain order");return Outcome::Rejected;}if(!foundExact){std::string code=foundCompeting?"PREPARED_TXID_ABSENT_COMPETING_BATCH_ANCHOR_PRESENT":"CONFIRMED_ANCHOR_ABSENT_FROM_CANONICAL_VIEW";if(!persistRecoveryRequired(db,i,code,expectedTxid,v,r))return Outcome::Rejected;setR(r,code+": recovery required; prepared/watch preserved; automatic re-anchor forbidden");return Outcome::RecoveryRequired;}return materializeConfirmed(db,i,proof,h,root,r);}catch(const std::exception&e){setR(r,std::string("sensor closeout exception contained: ")+e.what());return Outcome::Rejected;}}
}
