#include "vah_sensor_batch_anchor.h"
#include "blockchain.h"
#include "leveldb_storage.h"
#include "tx.h"
#include <algorithm>
#include <stdexcept>
namespace {
void setR(std::string*r,const std::string&s){if(r)*r=s;}
bool hx64(const std::string&s){return s.size()==64&&std::all_of(s.begin(),s.end(),[](unsigned char c){return (c>='0'&&c<='9')||(c>='a'&&c<='f');});}
std::vector<VAHSensorBatchAnchor::OutputSnapshot> outs(const Transaction&t){std::vector<VAHSensorBatchAnchor::OutputSnapshot>v;for(auto&o:t.vout)v.push_back({o.amount,o.scriptPubKey});return v;}
bool exactStored(LevelDBStorage&db,const VAHSensorBatchAccumulator::StoredBatch&s,const std::vector<VAHAuthorization::AuthorizationRecord>&h,const std::string&root,std::string*r){if(s.batch.events.empty()){setR(r,"stored sensor batch has no events");return false;}VAHSensorBatchAccumulator::StoredBatch x;if(!VAHSensorBatchAccumulator::loadStoredBatch(db,s.batch.token_id,s.batch.writer_id,s.batch.events.front().sequence,s.batch.batch_hash,h,root,x,r))return false;if(VAHSensorBatchAccumulator::serializeStoredBatch(x)!=VAHSensorBatchAccumulator::serializeStoredBatch(s)){setR(r,"supplied sensor batch differs from exact durable 04B record");return false;}return true;}
bool canonicalSubmission(const Transaction&supplied,const VAHSensorBatchAccumulator::StoredBatch&s,Transaction&canonical,std::string*r){if(supplied.isCoinbase||supplied.vin.empty()){setR(r,"prepared sensor anchor must be funded non-coinbase transaction");return false;}const std::string callerTxid=supplied.txid;canonical=supplied;canonical.computeTxId();if(!hx64(canonical.txid)){setR(r,"prepared sensor anchor recomputed txid invalid");return false;}if(!callerTxid.empty()&&callerTxid!=canonical.txid){setR(r,"prepared sensor anchor caller txid mismatch");return false;}if(!VAHSensorBatchAnchor::verifyPreparedAnchorOutputs(outs(canonical),s,r))return false;return true;}
std::string encodeHex(const std::string&s){static const char*d="0123456789abcdef";std::string o;o.reserve(s.size()*2);for(unsigned char c:s){o.push_back(d[c>>4]);o.push_back(d[c&15]);}return o;}
bool decodeHex(const std::string&h,std::string&o){if(h.empty()||h.size()%2)return false;o.clear();o.reserve(h.size()/2);for(size_t i=0;i<h.size();i+=2){auto cv=[](char c)->int{if(c>='0'&&c<='9')return c-'0';if(c>='a'&&c<='f')return c-'a'+10;return -1;};int a=cv(h[i]),b=cv(h[i+1]);if(a<0||b<0)return false;o.push_back(char((a<<4)|b));}return true;}
bool recoverTx(LevelDBStorage&db,const VAHSensorBatchAccumulator::StoredBatch&s,Transaction&tx,std::string*r){VAHSensorBatchAnchor::DurableAnchorState st;if(!VAHSensorBatchAnchor::loadPreparedWatch(db,s,st,r))return false;std::string ser;if(!decodeHex(st.tx_serialized_hex,ser)){setR(r,"sensor anchor prepared transaction hex invalid");return false;}try{tx=Transaction::deserialize(ser);}catch(const std::exception&e){setR(r,std::string("sensor anchor prepared transaction deserialize failed: ")+e.what());return false;}const std::string storedTxid=tx.txid;tx.computeTxId();if(!hx64(tx.txid)||tx.txid!=st.txid||storedTxid!=st.txid){setR(r,"sensor anchor recovered transaction txid mismatch");return false;}if(tx.serialize()!=ser){setR(r,"sensor anchor recovered transaction is not exact serialization roundtrip");return false;}if(!VAHSensorBatchAnchor::verifyPreparedAnchorOutputs(outs(tx),s,r))return false;return true;}
}
namespace VAHSensorBatchAnchor {
bool submitPreparedAnchor(Blockchain&chain,LevelDBStorage&db,const VAHSensorBatchAccumulator::StoredBatch&s,const std::vector<VAHAuthorization::AuthorizationRecord>&h,const std::string&root,const Transaction&t,std::string*r){if(r)r->clear();if(!exactStored(db,s,h,root,r))return false;Transaction canonical(false);if(!canonicalSubmission(t,s,canonical,r))return false;const std::string serialized=canonical.serialize();if(!persistPreparedWatch(db,s,canonical.txid,serialized,r))return false;/* 04C.1: this exact object has computeTxId() materialized above and is the object handed to broadcast. */if(!chain.broadcastTransaction(canonical)){setR(r,"prepared sensor batch anchor rejected by local mempool/broadcast path; durable watch retained");return false;}return true;}
bool recoverPreparedAnchor(Blockchain&chain,LevelDBStorage&db,const VAHSensorBatchAccumulator::StoredBatch&s,const std::vector<VAHAuthorization::AuthorizationRecord>&h,const std::string&root,std::string*r){if(r)r->clear();if(!exactStored(db,s,h,root,r))return false;Transaction recovered(false);if(!recoverTx(db,s,recovered,r))return false;/* no funding, no signing: exact persisted transaction is rebroadcast */if(!chain.broadcastTransaction(recovered)){setR(r,"recovered sensor batch anchor rejected by local mempool/broadcast path; durable watch retained");return false;}return true;}
bool confirmPreparedAnchor(const Blockchain&chain,LevelDBStorage&db,const VAHSensorBatchAccumulator::StoredBatch&s,const std::vector<VAHAuthorization::AuthorizationRecord>&h,const std::string&root,const Transaction&t,const VAHReconciliation::CanonicalView&v,uint64_t first,std::string*r){if(r)r->clear();if(!exactStored(db,s,h,root,r))return false;Transaction canonical(false);if(!canonicalSubmission(t,s,canonical,r))return false;DurableAnchorState st;if(!loadPreparedWatch(db,s,st,r))return false;if(st.txid!=canonical.txid||st.tx_serialized_hex!=encodeHex(canonical.serialize())){setR(r,"confirmation transaction differs from durable prepared/watch identity");return false;}Transaction recovered(false);if(!recoverTx(db,s,recovered,r)||recovered.txid!=canonical.txid)return false;if(first>v.finalizedHeight||v.finalizedHeight-first+1>2048){setR(r,"sensor confirmation range invalid");return false;}std::vector<BlockSnapshot> bs;for(uint64_t ht=first;ht<=v.finalizedHeight;++ht){auto ob=chain.getBlockByHeight(ht);if(!ob){setR(r,"active-chain block missing during sensor confirmation");return false;}BlockSnapshot b;b.height=ht;b.blockHash=ob->blockHash;b.previousBlockHash=ob->header.prevHash;for(const auto&tx:ob->transactions){Transaction c=tx;c.computeTxId();TxSnapshot ts;ts.txid=c.txid;ts.outputs=outs(tx);b.transactions.push_back(std::move(ts));}bs.push_back(std::move(b));}if(chain.getBlockHashByHeight((int)v.finalizedHeight)!=v.finalizedBlockHash){setR(r,"active-chain finalized view changed during sensor confirmation");return false;}return confirmSnapshot(s,recovered.txid,v,bs,r);}
}
