#include "vah_sensor_batch_anchor.h"
#include "leveldb_storage.h"
#include "leveldb/write_batch.h"
#include <algorithm>
#include <iomanip>
#include <sstream>
#include <stdexcept>
namespace { void setR(std::string* r,const std::string&s){if(r)*r=s;} bool hx(const std::string&s,size_t n){return s.size()==n&&std::all_of(s.begin(),s.end(),[](unsigned char c){return (c>='0'&&c<='9')||(c>='a'&&c<='f');});} bool zero(const std::string&s){return s==std::string(64,'0');}
std::string hex(const std::string&s){static const char*d="0123456789abcdef";std::string o;o.reserve(s.size()*2);for(unsigned char c:s){o.push_back(d[c>>4]);o.push_back(d[c&15]);}return o;} bool unhex(const std::string&h,std::string&o){if(h.size()%2)return false;o.clear();for(size_t i=0;i<h.size();i+=2){auto cv=[](char c)->int{if(c>='0'&&c<='9')return c-'0';if(c>='a'&&c<='f')return c-'a'+10;return -1;};int a=cv(h[i]),b=cv(h[i+1]);if(a<0||b<0)return false;o.push_back(char((a<<4)|b));}return true;}
void push(std::string&raw,const std::string&s){size_t n=s.size();if(n<=75)raw.push_back(char(n));else if(n<=255){/* Defensive future support only: all TRU_SENSOR_BATCH_V1 fields are currently <=64 bytes, so canonical V1 never emits OP_PUSHDATA1. */raw.push_back(char(0x4c));raw.push_back(char(n));}else throw std::invalid_argument("sensor anchor field too large");raw+=s;} bool readp(const std::string&r,size_t&p,std::string&o){if(p>=r.size())return false;unsigned n=(unsigned char)r[p++];if(n==0x4c){if(p>=r.size())return false;n=(unsigned char)r[p++];if(n<=75)return false;}else if(n==0||n>75)return false;if(p+n>r.size())return false;o=r.substr(p,n);p+=n;return true;}
bool dec(const std::string&s,uint64_t&v){if(s.empty()||(s.size()>1&&s[0]=='0'))return false;v=0;for(char c:s){if(c<'0'||c>'9')return false;uint64_t d=c-'0';if(v>(UINT64_MAX-d)/10)return false;v=v*10+d;}return true;} std::string ds(uint64_t v){return std::to_string(v);} bool valid(const VAHSensorBatchAnchor::Anchor&a){return hx(a.token_id,16)&&(a.token_type=="SFT"||a.token_type=="NCFT")&&a.epoch&&hx(a.writer_id,64)&&a.first_sequence&&a.last_sequence>=a.first_sequence&&a.event_count&&a.event_count<=VAHSensorBatch::MAX_EVENTS_PER_BATCH&&a.last_sequence-a.first_sequence+1==a.event_count&&hx(a.previous_batch_hash,64)&&hx(a.merkle_root,64)&&!zero(a.merkle_root)&&hx(a.batch_hash,64)&&!zero(a.batch_hash);}}
namespace VAHSensorBatchAnchor {
Anchor canonicalAnchorForStoredBatch(const VAHSensorBatchAccumulator::StoredBatch&s){const auto&b=s.batch;if(b.events.empty())throw std::invalid_argument("stored sensor batch has no events");Anchor a{b.token_id,b.token_type,b.epoch,b.events.front().sequence,b.events.back().sequence,(uint64_t)b.events.size(),b.writer_id,b.previous_batch_hash,b.merkle_root,b.batch_hash};if(!valid(a))throw std::invalid_argument("stored sensor batch identity is not canonical");return a;}
std::string encodeAnchor(const Anchor&a){if(!valid(a))throw std::invalid_argument("sensor batch anchor is not canonical");std::string r;r.push_back(char(0x6a));push(r,SENSOR_BATCH_MARKER);push(r,a.token_id);push(r,a.token_type);push(r,ds(a.epoch));push(r,a.writer_id);push(r,ds(a.first_sequence));push(r,ds(a.last_sequence));push(r,ds(a.event_count));push(r,a.previous_batch_hash);push(r,a.merkle_root);push(r,a.batch_hash);return hex(r);}
ParseStatus parseAnchor(const std::string&h,Anchor&o,std::string&reason){reason.clear();std::string r;if(!unhex(h,r)||r.empty()||(unsigned char)r[0]!=0x6a)return ParseStatus::NotSensorBatchAnchor;size_t p=1;std::string m;if(!readp(r,p,m))return ParseStatus::NotSensorBatchAnchor;if(m!=SENSOR_BATCH_MARKER)return ParseStatus::NotSensorBatchAnchor;std::string e,fs,ls,ec;if(!readp(r,p,o.token_id)||!readp(r,p,o.token_type)||!readp(r,p,e)||!readp(r,p,o.writer_id)||!readp(r,p,fs)||!readp(r,p,ls)||!readp(r,p,ec)||!readp(r,p,o.previous_batch_hash)||!readp(r,p,o.merkle_root)||!readp(r,p,o.batch_hash)||p!=r.size()||!dec(e,o.epoch)||!dec(fs,o.first_sequence)||!dec(ls,o.last_sequence)||!dec(ec,o.event_count)||!valid(o)){reason="TRU_SENSOR_BATCH_V1 malformed/noncanonical";return ParseStatus::Malformed;}return ParseStatus::Valid;}
bool verifyPreparedAnchorOutputs(const std::vector<OutputSnapshot>&outs,const VAHSensorBatchAccumulator::StoredBatch&s,std::string*reason){try{if(outs.empty()||outs.size()>MAX_ANCHOR_TRANSACTION_OUTPUTS){setR(reason,"prepared sensor anchor output count invalid");return false;}std::string exp=encodeAnchor(canonicalAnchorForStoredBatch(s));size_t n=0;for(auto&o:outs){if(o.scriptPubKey==exp){if(o.amount){setR(reason,"sensor batch anchor output must carry zero TRU");return false;}++n;continue;}Anchor a;std::string rr;auto st=parseAnchor(o.scriptPubKey,a,rr);if(st!=ParseStatus::NotSensorBatchAnchor){setR(reason,"prepared transaction contains second/mismatched sensor batch anchor");return false;}}if(n!=1){setR(reason,"prepared transaction must contain exactly one canonical sensor batch anchor");return false;}return true;}catch(const std::exception&e){setR(reason,std::string("prepared sensor anchor canonicalization failed: ")+e.what());return false;}}
std::string preparedKey(const VAHSensorBatchAccumulator::StoredBatch&s){const auto&a=canonicalAnchorForStoredBatch(s);return "TOKEN:VAH_SENSOR_ANCHOR_PREPARED:"+a.token_id+":writer:"+a.writer_id+":batch:"+a.batch_hash;}
std::string watchKey(const VAHSensorBatchAccumulator::StoredBatch&s){const auto&a=canonicalAnchorForStoredBatch(s);return "TOKEN:VAH_SENSOR_ANCHOR_WATCH:"+a.token_id+":writer:"+a.writer_id+":batch:"+a.batch_hash;}
static std::string stateText(const char*magic,const VAHSensorBatchAccumulator::StoredBatch&s,const std::string&txid,const std::string&ser){const auto&a=canonicalAnchorForStoredBatch(s);if(!hx(txid,64)||ser.empty()||ser.size()>MAX_PREPARED_TX_BYTES)throw std::invalid_argument("sensor anchor durable state invalid");return std::string(magic)+"\n"+"token_id="+a.token_id+"\nwriter_id="+a.writer_id+"\nfirst_sequence="+ds(a.first_sequence)+"\nlast_sequence="+ds(a.last_sequence)+"\nbatch_hash="+a.batch_hash+"\nmerkle_root="+a.merkle_root+"\ntxid="+txid+"\ntx_serialized_hex="+hex(ser)+"\n";}
static bool parseState(const std::string&text,const char*magic,DurableAnchorState&o){if(text.empty()||text.back()!='\n'||text.find('\r')!=std::string::npos)return false;std::istringstream in(text);std::string line;if(!std::getline(in,line)||line!=magic)return false;std::vector<std::string> keys={"token_id","writer_id","first_sequence","last_sequence","batch_hash","merkle_root","txid","tx_serialized_hex"};std::vector<std::string> vals;for(auto&k:keys){if(!std::getline(in,line))return false;std::string pre=k+"=";if(line.rfind(pre,0)!=0)return false;vals.push_back(line.substr(pre.size()));}if(std::getline(in,line))return false;uint64_t fs=0,ls=0;if(!hx(vals[0],16)||!hx(vals[1],64)||!dec(vals[2],fs)||!dec(vals[3],ls)||!fs||ls<fs||!hx(vals[4],64)||zero(vals[4])||!hx(vals[5],64)||zero(vals[5])||!hx(vals[6],64)||vals[7].empty()||vals[7].size()>MAX_PREPARED_TX_BYTES*2||!hx(vals[7],vals[7].size()))return false;o={vals[0],vals[1],vals[4],vals[5],vals[6],vals[7],fs,ls};return true;}
bool persistPreparedWatch(LevelDBStorage&db,const VAHSensorBatchAccumulator::StoredBatch&s,const std::string&txid,const std::string&txSerialized,std::string*reason){try{const std::string p=stateText(PREPARED_MAGIC,s,txid,txSerialized),w=stateText(WATCH_MAGIC,s,txid,txSerialized),pk=preparedKey(s),wk=watchKey(s);std::string raw,oldp,oldw;bool fp=false,fw=false;if(!db.getRaw("contract:"+pk,raw,fp)||!db.getRaw("contract:"+wk,raw,fw)){setR(reason,"sensor anchor prepared/watch raw-state read failed");return false;}bool hp=false,hw=false;if(fp){hp=db.getContract(pk,oldp);if(!hp){setR(reason,"existing sensor anchor prepared state is checksum-invalid");return false;}}if(fw){hw=db.getContract(wk,oldw);if(!hw){setR(reason,"existing sensor anchor watch state is checksum-invalid");return false;}}if((hp&&oldp!=p)||(hw&&oldw!=w)){setR(reason,"conflicting durable sensor anchor state");return false;}if(hp&&hw){setR(reason,"already prepared/watched");return true;}leveldb::WriteBatch b;b.Put("contract:"+pk,db.computeDataChecksum(p)+"|"+p);b.Put("contract:"+wk,db.computeDataChecksum(w)+"|"+w);if(!db.putBatch(b,true)){setR(reason,"sensor anchor prepared/watch atomic batch refused");return false;}std::string rp,rw;if(!db.getContract(pk,rp)||!db.getContract(wk,rw)||rp!=p||rw!=w){setR(reason,"sensor anchor prepared/watch readback mismatch");return false;}return true;}catch(const std::exception&e){setR(reason,e.what());return false;}}
bool loadPreparedWatch(LevelDBStorage&db,const VAHSensorBatchAccumulator::StoredBatch&s,DurableAnchorState&o,std::string*reason){try{std::string p,w;if(!db.getContract(preparedKey(s),p)||!db.getContract(watchKey(s),w)){setR(reason,"missing/checksum-invalid sensor anchor prepared/watch state");return false;}DurableAnchorState a,b;if(!parseState(p,PREPARED_MAGIC,a)||!parseState(w,WATCH_MAGIC,b)){setR(reason,"malformed sensor anchor prepared/watch state");return false;}const auto&x=canonicalAnchorForStoredBatch(s);auto same=[&](const DurableAnchorState&q){return q.token_id==x.token_id&&q.writer_id==x.writer_id&&q.first_sequence==x.first_sequence&&q.last_sequence==x.last_sequence&&q.batch_hash==x.batch_hash&&q.merkle_root==x.merkle_root;};if(!same(a)||!same(b)||a.txid!=b.txid||a.tx_serialized_hex!=b.tx_serialized_hex){setR(reason,"sensor anchor prepared/watch identity mismatch");return false;}o=a;return true;}catch(const std::exception&e){setR(reason,std::string("sensor anchor prepared/watch canonicalization failed: ")+e.what());return false;}}
bool confirmSnapshot(const VAHSensorBatchAccumulator::StoredBatch&s,const std::string&txid,const VAHReconciliation::CanonicalView&v,const std::vector<BlockSnapshot>&bs,std::string*reason){try{if(!hx(txid,64)||bs.empty()||bs.size()>2048){setR(reason,"confirmation identity/range invalid");return false;}if(bs.back().height!=v.finalizedHeight||bs.back().blockHash!=v.finalizedBlockHash){setR(reason,"snapshot does not end at finalized view");return false;}for(size_t i=1;i<bs.size();++i)if(bs[i].height!=bs[i-1].height+1||bs[i].previousBlockHash!=bs[i-1].blockHash){setR(reason,"snapshot is not contiguous active-chain order");return false;}std::string exp=encodeAnchor(canonicalAnchorForStoredBatch(s));size_t found=0;for(auto&b:bs)for(auto&t:b.transactions)if(t.txid==txid){size_t exact=0;for(auto&o:t.outputs)if(o.scriptPubKey==exp&&o.amount==0)++exact;if(exact==1)++found;}if(found!=1){setR(reason,"exact sensor batch anchor txid not uniquely confirmed");return false;}return true;}catch(const std::exception&e){setR(reason,std::string("sensor anchor confirmation canonicalization failed: ")+e.what());return false;}}
}
